const mutations = {
  IS_LOGGED_IN: 'IS_LOGGED_IN',
  IS_LOGIN_IN_PROGRESS: 'IS_LOGIN_IN_PROGRESS',
  SHOW_NOTIFY: 'SHOW_NOTIFY',
  USER: 'USER',
  IS_FIRST_LOGIN: 'IS_FIRST_LOGIN'
}

export default mutations
